ROSTemplateFormatVersion: '2015-09-01'
# 定义参数
Parameters:
  RoleName:
    Type: String
    AssociationProperty: ALIYUN::RAM::Service::Role
    AssociationPropertyMetadata:
      Service: supplier.computenest.aliyuncs.com
      APIProduct: resourcegroup
      IsServiceLinedRole: false
    Description: 请前往RAM控制台创建角色，角色需拥有上述模板定义的资源所需的创建权限。<a href='https://help.aliyun.com/zh/compute-nest/create-a-compute-nest-ram-role-and-grant-permissions-to-the-role' target='_blank'><b> 查看文档</b><font color='blue'></a>