Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      RoleName: ComputeNestDeploy
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: Template
          Url: 'ros_templates/template.yaml'
          PredefinedParameters: []
          HiddenParameterKeys:
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: vpc-bp10gk7drwi4ecuexqgls
                    ZoneId: cn-hangzhou-g
                    VSwitchId: vsw-bp1newlcpcby20si43l3w
      FileArtifactRelation:
        '{{ computenest::file::aliyun-computenest_mysql-managed-vpcpeering-demo }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: Template
        ArchitectureDiagramUrl: 'docs/architecture.png'
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: aliyun-computenest_mysql-managed-vpcpeering-demo
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/aliyun-computenest_mysql-managed-vpcpeering-demo.tar.gz'