Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: mysql-
    SupplierDeployMetadata:
      UserType: Aliyun
      RoleName: ${RoleName}
      SupplierTemplateConfigs:
        - Name: Template
          Url: 'ros_templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 该套餐采用了2vCPU 4GB内存的ECS实例（ecs.c6.large），满足基本的业务需求。
              Parameters:
                EcsInstanceType: ['ecs.c6.large']
              Type: Normal
              OrderList:
                - EcsInstanceType
            - Name: 基础版
              Description: 该套餐采用了4vCPU 8GB内存的ECS实例（ecs.c6.xlarge），该配置可以满足大部分的业务需求。
              Parameters:
                EcsInstanceType: ['ecs.c6.xlarge']
              Type: Normal
              OrderList:
                - EcsInstanceType
            - Name: 高配版
              Description: 该套餐采用了8vCPU 16GB内存的ECS实例（ecs.c6.2xlarge），该配置使用了更高规格ECS，进一步提升了架构的稳定性和性能。
              Parameters:
                EcsInstanceType: ['ecs.c6.2xlarge']
              Type: Normal
              OrderList:
                - EcsInstanceType
          HiddenParameterKeys:
            - EcsInstanceType
      FileArtifactRelation:
        '{{ computenest::file::MySQL }}':
          ArtifactId: artifact-294b0a26e269458eb6b9
    TemplateConfigs:
      - Name: Template
        ArchitectureDiagramUrl: 'docs/architecture.jpg'
        AllowedRegions:
          - cn-qingdao
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-nanjing
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - na-south-1
          - eu-west-1
          - me-east-1
          - me-central-1
          - eu-central-1
    NetworkMetadata:
      EnablePrivateVpcConnection: true
      EnableReversePrivateVpcConnection: false
      PrivateVpcConnectionMode: VpcPeering
  ServiceType: managed
  UpgradeMetadata:
    Description: 升级
    SupportRollback: true
    SupportUpgradeFromVersions: [ ]
    UpgradeComponents:
      - Configuration
      - Resource
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: mysql demo
    Image: 'resources/icons/service_logo.jpg'
    Name: MySQL托管版beta1
  ShareType: Public
  ApprovalType: Manual
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: Template
        Operation:
          - Name: 网络变配
            Description: 网络变配支持VpcPeering新增、删除、修改
            Type: Custom
            EnablePrivateVpcConnection: true
